/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:97483b1e-28b9-46a3-bc55-ccbf2ee909f0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_O7ki30pfV",
    "aws_user_pools_web_client_id": "39nafsjlhp2fbr0k1va4uvhn8m",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "showbizzz78e21b69aad340968a87057c0f4d287a214359-prod",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
